name: Run Gitracker

on:
  push:
    branches:
      - master
      - develop

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Gitracker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_WEBHOOK_SECRET: ${{ secrets.GITHUB_WEBHOOK_SECRET }}
          WEBHOOK_TITLE: ${{ secrets.WEBHOOK_TITLE }} # Title of the base embed.
          WEBHOOK_COLOR: ${{ secrets.WEBHOOK_COLOR }} # Color of the embed(s).
          DENY_SPLITTING: ${{ secrets.DENY_SPLITTING }} # Whether to deny splitting the embed(s). (EXPERIMENTAL)
        run: node bot.js

permissions:
  contents: read
  pull-requests: read
  issues: read
